# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Class Name')),
                ('time', models.DateTimeField(verbose_name='Class Time')),
                ('point1', models.CharField(max_length=256, verbose_name='BulletPoint1')),
                ('point2', models.CharField(max_length=256, verbose_name='BulletPoint2')),
                ('point3', models.CharField(max_length=256, verbose_name='BulletPoint3')),
                ('point4', models.CharField(max_length=256, verbose_name='BulletPoint4')),
                ('point5', models.CharField(max_length=256, verbose_name='BulletPoint5')),
            ],
        ),
    ]
